#pragma config(Sensor, S1,     sonar,          sensorSONAR)
#pragma config(Sensor, S2,     none,           sensorNone)
#pragma config(Sensor, S3,     none,           sensorNone)
#pragma config(Sensor, S4,     none,           sensorNone)
#pragma config(Motor,  motorA,          claw,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/////////////////////
//	Task: Main
// 	Desc:
////////////////////
task main()
{
	wait1Msec(1000);
	motor[left] = 50;
	motor[right] = 50;
	for (int i = 0; i < 10; i++)
	{
		wait1Msec(1000);
	}
	motor[left] = 0;
	motor[right] = 0;
}
